mutation {
  signUp(
    email: "finit@gmail.com"
    name: "Finit"
    username: "finit"
    password: "Finit7331!"
  ) {
    id
  }
}

mutation {
  signIn(email: "finit@gmail.com", password: "Finit7331!") {
    id
  }
}

mutation {
  signOut
}

mutation {
  addAccount(
    plaidItemId: "12312312"
    accountId: "12312312"
    userId: "5f0f18dd2e6b6b1e6e69dd54"
    mask: "mask"
    balances: "10000"
    name: "name"
    officialName: "officialName"
    type: "type"
    subtype: "subtype"
  ) {
    id
    name
  }
}

mutation {
  addTransaction(
    userId: "5f759a64278ebc612d6141b8"
    accountId: "asdasd"
    amount: "50"
    category: ["Health", "Care"]
    date: "2020-8-12"
    isoCurrencyCode: "USD"
    name: "Netflix"
    paymentChannel: "from home"
    transactionId: "asd6as8d6a78s6"
    transactionType: "special"
  ) {
    name
    amount
  }
}

{
  accounts(userId: "5f0f18dd2e6b6b1e6e69dd54") {
    name
    officialName
  }
}

{
  me {
    id
    name
    email
  }
}

{
  users {
    id
  }
}

{
  user(id: "5f218c1e3fffd56ef2f45075") {
    id
  }
}
